#!/usr/bin/env groovy

pipeline {
  agent any

  stages {
    stage('Build') {
      steps {
        configFileProvider([configFile(fileId: 'HadithHouse-server_settings.py-Dev', variable: 'SERVER_SETTINGS_PATH')]) {
          sh('''cd HadithHouseWebsite
chmod +x build.sh
./build.sh''')
        }
      }
    }
  }
}
