# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadiths', '0002_create_admin_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'default_permissions': ('add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='chain',
            options={'default_permissions': ('add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='chainlink',
            options={'default_permissions': ('add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='hadith',
            options={'default_permissions': ('add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='hadithtag',
            options={'default_permissions': ('add', 'change', 'delete')},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'default_permissions': ('add', 'change', 'delete')},
        ),
        migrations.AddField(
            model_name='hadith',
            name='simple_text',
            field=models.TextField(db_index=True, default=b''),
        ),
    ]
