# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadiths', '0003_add_simple_text_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='simple_brief_desc',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='simple_title',
            field=models.CharField(default=b'', max_length=128),
        ),
        migrations.AddField(
            model_name='hadithtag',
            name='simple_name',
            field=models.CharField(default=b'', max_length=32),
        ),
        migrations.AddField(
            model_name='person',
            name='simple_brief_desc',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='simple_display_name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='person',
            name='simple_full_name',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
