# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hadiths', '0006_20160207_setfirsthadithsbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainlink',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chainlinks', to='hadiths.Person'),
        ),
        migrations.AlterField(
            model_name='hadith',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hadiths', to='hadiths.Book'),
        ),
        migrations.AlterField(
            model_name='hadith',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hadiths', to='hadiths.Person'),
        ),
    ]
