# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadiths', '0007_20160207_setfirsthadithsbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='added_by',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_year',
            field=models.SmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_by',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='hadith',
            name='added_by',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='hadith',
            name='text',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='hadith',
            name='updated_by',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='hadithtag',
            name='added_by',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='hadithtag',
            name='updated_by',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='added_by',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_by',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fb_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
